version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    target-branch: main
    labels:
      - "dependencies"
      - "skip-changelog"
