version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      day: sunday
      interval: weekly
    labels:
      - dependabot-deps-updates
      - skip-changelog
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "dependencies"
      - "skip-changelog"
