---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  pep8:
    enabled: true
exclude_paths:
- ".cache/**/*"
- ".git/**/*"
- ".tox/**/*"
- "build/**/*"
- "dist/**/*"
