---
ci:
  # We rely on renovate to update it but there is no way to fully disable it
  # https://github.com/pre-commit-ci/issues/issues/83
  autoupdate_schedule: quarterly
  skip:
    - cspell # missing uv
    - codecov # missing uv
    - shellcheck # no docker support on pre-commit.ci
    # uv not present on pre-commit.ci
    - mypy
    - pylint
    - ruff
    - toml
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
        priority: 0
  - repo: https://github.com/ansible/actions
    rev: v1.0.1
    hooks:
      - id: toml
        priority: 0
      - id: mypy
        priority: 2
      - id: ruff
        priority: 1
      - id: cspell
        priority: 0
      # - id: pylint
      #   priority: 5
      - id: codecov
        priority: 0
      - id: codespell
        priority: 0
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        priority: 0
      - id: check-merge-conflict
        priority: 0
      - id: check-symlinks
        priority: 0
      - id: debug-statements
        priority: 0
      - id: end-of-file-fixer
        priority: 1
      - id: trailing-whitespace
        priority: 1
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-yaml
        files: .*\.(yaml|yml)$
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: 1.6.0
    hooks:
      - id: tox-ini-fmt
