---
version: 2

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    # PIP_CONSTRAINT has been set as env variable in the RTD web interface
    - method: pip
      path: .
      extra_requirements:
        - docs
