---
version: 2

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  # PIP_CONSTRAINT=constraints.txt set in the RTD web interface
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
