---
version: 2

formats: all

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  apt_packages:
    - libkrb5-dev

python:
  install:
    - requirements: .config/constraints.txt
    - path: .
      extra_requirements:
        - docs
        # to autodoc jirashell
        - cli

sphinx:
  configuration: docs/conf.py
