# See https://github.com/ansible/team-devtools/blob/main/.github/workflows/ack.yml
name: ack
on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  ack:
    uses: "https://raw.githubusercontent.com/ansible/team-devtools/refs/heads/main/.github/workflows/ack.yml"
    secrets: inherit
