name: ci

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  server:
    uses: pycontribs/jira/.github/workflows/jira_server_ci.yml@main

  cloud:
    needs: server
    uses: pycontribs/jira/.github/workflows/jira_cloud_ci.yml@main
    secrets:
      CLOUD_ADMIN: ${{ secrets.CI_JIRA_CLOUD_ADMIN }}
      CLOUD_ADMIN_TOKEN: ${{ secrets.CI_JIRA_CLOUD_ADMIN_TOKEN }}
      CLOUD_USER: ${{ secrets.CI_JIRA_CLOUD_USER }}
      CLOUD_USER_TOKEN: ${{ secrets.CI_JIRA_CLOUD_USER_TOKEN }}

  # 'check' the only job that should be marked as required in
  # repository config, so we do not need to change required jobs
  # when we add new/remove/rename jobs.
  check:
    needs:
      - cloud
    runs-on: ubuntu-latest

    steps:
      - name: Report success of the test matrix
        run: >-
          print("All's good")
        shell: python
